-- 코드를 입력하세요
SELECT CAR_ID, CASE WHEN
CAR_ID NOT IN  (
    -- 2022년 10월 16일에 대출 기록이 있는 차량번호를 찾는 쿼리
    -- 여기 나오는 차량번호 목록에 없는 차량이 대여 가능한 쿼리
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE '20221016' BETWEEN TO_CHAR(START_DATE,'YYYYMMDD') AND TO_CHAR(END_DATE,'YYYYMMDD')) THEN '대여 가능'
ELSE '대여중'
END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;