spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/utilJPA01
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true
  #        show_sql: true


#      Systemout을 통해 출력하기 때문에 log를 통해서 찍어야 한다.
#      show_sql: true

logging:
  level:
    org.hibernate.SQL: debug
