SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES

FROM BOOK A     JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
                JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
                
WHERE TO_CHAR(C.SALES_DATE,'YYYY-MM') ='2022-01'

GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY

ORDER BY A.AUTHOR_ID ASC , A.CATEGORY DESC



/*
ELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, 
       SUM(B.PRICE * S.SALES) AS TOTAL_SALES

FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
            JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID

WHERE TO_CHAR(SALES_DATE, 'YYYYMM') = '202201'

GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY  

ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;
*/

