spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
        use_sql_comments: true
    open-in-view: false

  #  ??? ??? ???
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true
#        ??? ???? page? ??? 1?? ???? ??? 0

logging:
  level:
    org.hibernate.sql : debug
    org.hibernate.type : trace



