--------------------------------------------------------
--  파일이 생성됨 - 월요일-7월-03-2023   
--------------------------------------------------------
DROP SEQUENCE "C##ITBANK"."PHONEBOOK_SEQ";
DROP SEQUENCE "C##ITBANK"."PRODUCT_SEQ";
DROP SEQUENCE "C##ITBANK"."SALES_SEQ";
DROP TABLE "C##ITBANK"."PHONEBOOK";
DROP TABLE "C##ITBANK"."PRODUCT";
DROP TABLE "C##ITBANK"."SALES";
DROP TABLE "C##ITBANK"."STUDENT";
--------------------------------------------------------
--  DDL for Sequence PHONEBOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITBANK"."PHONEBOOK_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITBANK"."PRODUCT_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 9 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SALES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##ITBANK"."SALES_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 19 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table PHONEBOOK
--------------------------------------------------------

  CREATE TABLE "C##ITBANK"."PHONEBOOK" 
   (	"IDX" NUMBER DEFAULT "C##ITBANK"."PHONEBOOK_SEQ"."NEXTVAL", 
	"NAME" VARCHAR2(100 BYTE), 
	"AGE" NUMBER, 
	"PNUM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "C##ITBANK"."PRODUCT" 
   (	"IDX" NUMBER DEFAULT "C##ITBANK"."PRODUCT_SEQ"."NEXTVAL", 
	"NAME" VARCHAR2(100 BYTE), 
	"PRICE" NUMBER, 
	"EXPDATE" DATE, 
	"MEMO" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SALES
--------------------------------------------------------

  CREATE TABLE "C##ITBANK"."SALES" 
   (	"IDX" NUMBER DEFAULT "C##ITBANK"."SALES_SEQ"."NEXTVAL", 
	"SALESDATE" DATE DEFAULT sysdate, 
	"PRODUCT" NUMBER, 
	"CNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "C##ITBANK"."STUDENT" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"SCORE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##ITBANK.PHONEBOOK
SET DEFINE OFF;
Insert into C##ITBANK.PHONEBOOK (IDX,NAME,AGE,PNUM) values (1,'이지은',31,'010-1234-4321');
Insert into C##ITBANK.PHONEBOOK (IDX,NAME,AGE,PNUM) values (2,'홍길동',22,'010-4444-3333');
Insert into C##ITBANK.PHONEBOOK (IDX,NAME,AGE,PNUM) values (3,'홍진호',42,'010-2222-2222');
commit;
REM INSERTING into C##ITBANK.PRODUCT
SET DEFINE OFF;
Insert into C##ITBANK.PRODUCT (IDX,NAME,PRICE,EXPDATE,MEMO) values (1,'초코파이',3500,to_date('24/01/01','RR/MM/DD'),'초코파이 12p');
Insert into C##ITBANK.PRODUCT (IDX,NAME,PRICE,EXPDATE,MEMO) values (2,'몽쉘',4000,to_date('23/12/31','RR/MM/DD'),'몽쉘 12p');
Insert into C##ITBANK.PRODUCT (IDX,NAME,PRICE,EXPDATE,MEMO) values (3,'페레로로쉐',1200,to_date('23/12/31','RR/MM/DD'),'페레로로쉐 3p');
Insert into C##ITBANK.PRODUCT (IDX,NAME,PRICE,EXPDATE,MEMO) values (4,'코카콜라',1200,to_date('23/12/31','RR/MM/DD'),'코카콜라 캔');
Insert into C##ITBANK.PRODUCT (IDX,NAME,PRICE,EXPDATE,MEMO) values (5,'펩시콜라',1200,to_date('24/06/01','RR/MM/DD'),'펩시콜라 캔');
Insert into C##ITBANK.PRODUCT (IDX,NAME,PRICE,EXPDATE,MEMO) values (6,'맥콜',900,to_date('24/06/01','RR/MM/DD'),'맥콜 캔');
Insert into C##ITBANK.PRODUCT (IDX,NAME,PRICE,EXPDATE,MEMO) values (7,'칠성 사이다 제로',3200,to_date('24/01/01','RR/MM/DD'),'칠성사이다 1.5 PET');
Insert into C##ITBANK.PRODUCT (IDX,NAME,PRICE,EXPDATE,MEMO) values (8,'환타',2900,to_date('24/01/01','RR/MM/DD'),'환타 1.5 PET');
commit;
REM INSERTING into C##ITBANK.SALES
SET DEFINE OFF;
Insert into C##ITBANK.SALES (IDX,SALESDATE,PRODUCT,CNT) values (13,to_date('23/07/03','RR/MM/DD'),1,5);
Insert into C##ITBANK.SALES (IDX,SALESDATE,PRODUCT,CNT) values (14,to_date('23/07/03','RR/MM/DD'),7,2);
Insert into C##ITBANK.SALES (IDX,SALESDATE,PRODUCT,CNT) values (15,to_date('23/07/03','RR/MM/DD'),5,3);
Insert into C##ITBANK.SALES (IDX,SALESDATE,PRODUCT,CNT) values (16,to_date('23/07/03','RR/MM/DD'),3,10);
Insert into C##ITBANK.SALES (IDX,SALESDATE,PRODUCT,CNT) values (17,to_date('23/07/01','RR/MM/DD'),4,5);
Insert into C##ITBANK.SALES (IDX,SALESDATE,PRODUCT,CNT) values (18,to_date('23/07/01','RR/MM/DD'),6,2);
commit;
REM INSERTING into C##ITBANK.STUDENT
SET DEFINE OFF;
Insert into C##ITBANK.STUDENT (NAME,SCORE) values ('이지은',95);
Insert into C##ITBANK.STUDENT (NAME,SCORE) values ('홍진호',22);
Insert into C##ITBANK.STUDENT (NAME,SCORE) values ('김지수',96);
commit;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "C##ITBANK"."PRODUCT" MODIFY ("MEMO" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."PRODUCT" ADD CHECK (price >= 100) ENABLE;
  ALTER TABLE "C##ITBANK"."PRODUCT" ADD CHECK (expDate > to_date('2023/07/01', 'YYYY/MM/DD')) ENABLE;
  ALTER TABLE "C##ITBANK"."PRODUCT" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITBANK"."PRODUCT" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHONEBOOK
--------------------------------------------------------

  ALTER TABLE "C##ITBANK"."PHONEBOOK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."PHONEBOOK" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."PHONEBOOK" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."PHONEBOOK" ADD CHECK (0<age and age < 120) ENABLE;
  ALTER TABLE "C##ITBANK"."PHONEBOOK" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##ITBANK"."PHONEBOOK" ADD UNIQUE ("PNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "C##ITBANK"."SALES" MODIFY ("PRODUCT" NOT NULL ENABLE);
  ALTER TABLE "C##ITBANK"."SALES" ADD CHECK (cnt > 0) ENABLE;
  ALTER TABLE "C##ITBANK"."SALES" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SALES
--------------------------------------------------------

  ALTER TABLE "C##ITBANK"."SALES" ADD CONSTRAINT "SALE_PRODUCT_FK" FOREIGN KEY ("PRODUCT")
	  REFERENCES "C##ITBANK"."PRODUCT" ("IDX") ENABLE;

commit;