spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/SpringData
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect

logging:
  level:
    org.hibernate.sql : debug
    org.hibernate.type : trace



