-- 코드를 입력하세요

SELECT ANIMAL_ID, NAME
FROM(
SELECT B.ANIMAL_ID, B.NAME, ROUND(TO_NUMBER(B.DATETIME-A.DATETIME),2) AS DD
FROM
ANIMAL_INS A 
RIGHT JOIN 
ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME IS NOT NULL
ORDER BY DD DESC
FETCH NEXT 2 ROWS ONLY
    )
    
    